// <auto-generated />
using System;
using KMITL_WebDev_MiniProject.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MvcMovie.Migrations.Reputations
{
    [DbContext(typeof(ApplicationReputationsDbContext))]
    partial class ApplicationReputationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KMITL_WebDev_MiniProject.Entites.ReputationRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Relation")
                        .HasColumnType("int");

                    b.Property<Guid>("UserObj")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserSub")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("ReputationRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
